project:
  type: website
  output-dir: docs
  
website:
  title: "STORYTELLING WITH R GRAPHS AND ChatGPT"
  site-url: "https://bougioukas.github.io/storytelling/"
  favicon: "img/logo.png"
  navbar:
    right:
      - text: Tables
        menu:
          - text: Table1
            href: projects.qmd
          - text: Table2
            href: projects2.qmd
      - text: Basic
        menu:
          - text: Area plot
            href: projects.qmd
          - text: Bar plot
            href: projects.qmd            
          - text: Box plot
            href: projects.qmd
          - text: Density plot
            href: projects2.qmd                  
          - text: Dot plot
            href: projects.qmd
          - text: Heatmap
            href: projects2.qmd
          - text: Histogram
            href: projects2.qmd   
          - text: Line chart
            href: projects2.qmd
          - text: Pie chart
            href: projects2.qmd
          - text: Q-Q plot
            href: projects2.qmd
          - text: Radar plot
            href: projects2.qmd            
          - text: Scatter plot
            href: projects2.qmd
          - text: Venn/Euler diagram
            href: projects2.qmd 
          - text: Violin plot
            href: projects.qmd            
      - text: Specialized
        menu:
          - text: Bland-Altman plot
            href: projects.qmd
          - text: Bubble plot
            href: projects.qmd            
          - text: Correlation matrix
            href: projects.qmd
          - text: Doughnut chart
            href: projects2.qmd
          - text: Epidemic curve
            href: projects2.qmd            
          - text: Likert plot
            href: projects2.qmd            
          - text: Mosaic plot
            href: projects2.qmd
          - text: Pyramid plot
            href: projects2.qmd              
          - text: Raincloud plot
            href: projects2.qmd
          - text: Ridgeline chart
            href: projects2.qmd                
          - text: ROC curve
            href: projects2.qmd
          - text: Survival plot
            href: projects2.qmd
          - text: Upset plot
            href: projects2.qmd                  
          - text: Waterfall chart
            href: projects2.qmd            
      - text: Networks
        menu:
          - text: Alluvial Diagrams
            href: projects.qmd        
          - text: Chord diagram
            href: projects.qmd
          - text: Graph/Network
            href: projects2.qmd
          - text: Shankey diagram
            href: projects2.qmd 
      - text: Tree-based
        menu:
          - text: Circular packing
            href: projects.qmd         
          - text: Radial tree
            href: projects.qmd 
          - text: Treemap  
            href: projects.qmd
          - text: Voroni diagram
            href: projects.qmd              
      - text: Maps
        menu:
          - text: Bubble map
            href: projects.qmd
          - text: Choropleth map
            href: projects.qmd            
          - text: Choropleth map
            href: projects.qmd            
          - text: Flow map
            href: projects2.qmd              
          - text: Isopleth map
            href: projects2.qmd
      - text: Evidence synthesis
        menu:
          - text: Albatross plot
            href: projects.qmd
          - text: Baujat plot
            href: projects.qmd
          - text: CCA heatmap
            href: projects.qmd               
          - text: Components cross-table
            href: projects.qmd   
          - text: Cross-hairs scatter plot
            href: projects.qmd            
          - text: CUMSUM chart
            href: projects.qmd             
          - text: Forest plot
            href: projects.qmd
          - text: Funnel plot
            href: projects2.qmd
          - text: Fuzzy number plot
            href: projects2.qmd            
          - text: Galbraith/radial plot
            href: projects2.qmd
          - text: GOSH plot
            href: projects2.qmd
          - text: Harvest plot
            href: projects2.qmd 
          - text: Kilim plot
            href: projects2.qmd             
          - text: L’Abbé plot 
            href: projects2.qmd
          - text: Netheat plot
            href: projects2.qmd
          - text: Rank-heat plot 
            href: projects2.qmd             
      - text: Other
        menu:
          - text: Fagan's nomogram
            href: projects.qmd             
          - text: Gantt Chart
            href: projects.qmd
          - text: Word cloud
            href: projects.qmd               
    pinned: true
    logo: "img/logo.png"
    tools:
      - icon: github
        href: https://github.com/bougioukas/storytelling
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)^®^"
    left: "&copy; Copyright 2024, Konstantinos I. Bougioukas. License: [Creative Commons Attribution-NonCommercial-NoDerivs 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/)."
  back-to-top-navigation: true
format:
  html:
    smooth-scroll: true
    theme:
      - custom.scss
    link-external-newwindow: true
    toc: true
    citations-hover: true
    footnotes-hover: true
    code-link: true

editor: source

