project:
  type: website
  output-dir: docs
  
website:
  title: "STORYTELLING WITH DATA AND COLORS"
  site-url: "https://bougioukas.github.io/storytelling/"
  navbar:
    right:
      - text: Choropleth maps
        menu:
          - text: projects1
            href: projects.qmd
          - text: projects2
            href: projects2.qmd
    pinned: true
    tools:
      - icon: github
        href: https://github.com/bougioukas/storytelling
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Konstantinos I. Bougioukas"

format:
  html:
    smooth-scroll: true
    theme:
      - custom.scss
    link-external-newwindow: true 
    toc: true
    citations-hover: true
    footnotes-hover: true
    code-link: true

editor: source

