project:
  type: website
  output-dir: docs
  
website:
  title: "STORYTELLING WITH DATA, SHAPES, AND COLORS"
  site-url: "https://bougioukas.github.io/storytelling/"
  favicon: "img/logo.png"
  navbar:
    right:
      - text: Tables
        menu:
          - text: projects1
            href: projects.qmd
          - text: projects2
            href: projects2.qmd
      - text: Statistical Plots
        menu:
          - text: projects1
            href: projects.qmd
          - text: projects2
            href: projects2.qmd      
      - text: Networks
        menu:
          - text: projects1
            href: projects.qmd
          - text: projects2
            href: projects2.qmd
      - text: Maps
        menu:
          - text: projects1
            href: projects.qmd
          - text: projects2
            href: projects2.qmd 
      - text: Interactive Plots
        menu:
          - text: projects1
            href: projects.qmd
          - text: projects2
            href: projects2.qmd          
    pinned: true
    tools:
      - icon: github
        href: https://github.com/bougioukas/storytelling
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)^®^"
    left: "&copy; Copyright 2024, Konstantinos I. Bougioukas. License: [Creative Commons Attribution-NonCommercial-NoDerivs 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/)."
  back-to-top-navigation: true
format:
  html:
    smooth-scroll: true
    theme:
      - custom.scss
    link-external-newwindow: true
    toc: true
    citations-hover: true
    footnotes-hover: true
    code-link: true

editor: source

